In [2]:
import pandas as pd

# Part A:Initial Cleaning

In [3]:
df = pd.read_csv('project.csv')
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Id                20 non-null     int64
 1   Name              19 non-null     object
 2   Age               16 non-null     float64
 3   Gender            20 non-null     object
 4   Salary            19 non-null     object
 5   Department        20 non-null     object
 6   JoiningDate       19 non-null     object
 7   PerformanceScore  16 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 1.4+ KB

             Id         Age
count  20.00000   16.000000
mean   10.50000   53.812500
std     5.91608   48.100199
min     1.00000   22.000000
25%     5.75000   28.000000
50%    10.50000   32.000000
75%    15.25000   45.000000
max    20.00000  150.000000

In [4]:
#Converting data types to numeric
df['Age'] = pd.to_numeric(df['Age'], errors = 'coerce')
df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')
df['PerformanceScore'] = pd.to_numeric(df['PerformanceScore'], errors = 'coerce')
df.describe()

             Id         Age          Salary  PerformanceScore
count  20.00000   16.000000       16.000000         15.000000
mean   10.50000   53.812500   129687.500000         10.200000
std     5.91608   48.100199   233141.364484          4.091804
min     1.00000   22.000000    50000.000000          6.000000
25%     5.75000   28.000000    57500.000000          7.500000
50%    10.50000   32.000000    70000.000000          8.000000
75%    15.25000   45.000000    82500.000000         12.500000
max    20.00000  150.000000  1000000.000000         20.000000

In [5]:
# Handling the Missing Values
thres = len(df) * 0.5

df = df.dropna(thresh = thres, axis = 1)

for col in df.columns:
    if df[col].dtype in ['float64', 'int64']:
        df[col].fillna(df[col].median(), inplace = True)
    else:
        df[col].fillna(df[col].mode()[0], inplace = True)

df

C:\Users\Acer\AppData\Local\Temp\ipykernel_8892\2273984070.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace = True)
C:\Users\Acer\AppData\Local\Temp\ipykernel_8892\2273984070.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace = True)
C:\Users\Acer\AppData\Local\Temp\ipykernel_8892\2273984070.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace = True)
C:\Users\Acer\AppData\Local\Temp\ipykernel_8892\2273984070.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace = True)
C:\Users\Acer\AppData\Local\Temp\ipykernel_8892\2273984070.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace = True)
C:\Users\Acer\AppData\Local\Temp\ipykernel_8892\2273984070.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace = True)
C:\Users\Acer\AppData\Local\Temp\ipykernel_8892\2273984070.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace = True)

,Id,Name,Age,Gender,Salary,Department,JoiningDate,PerformanceScore
0,1,John Doe,28.0,Male,50000.0,Sales,2018-05-10,8.0
1,2,Jane Smith,32.0,Female,60000.0,HR,2019-03-15,7.0
2,3,Bob Lee,150.0,Male,70000.0,IT,2017-11-20,15.0
3,4,Alice Wong,32.0,Female,70000.0,Finance,2020-01-01,8.0
4,5,John Doe,28.0,Male,50000.0,Sales,2018-05-10,8.0
5,6,Chris O'Neil,45.0,Male,120000.0,Marketing,2016-07-22,10.0
6,7,Sam,32.0,Unknown,80000.0,Operations,2018-12-12,8.0
7,8,Linda,29.0,Female,90000.0,HR,2019-08-30,9.0
8,9,Tom,22.0,Male,1000000.0,IT,2021-02-14,20.0
9,10,John Doe,35.0,Female,75000.0,Finance,2018-05-10,6.0
10,11,Jane Smith,32.0,Female,60000.0,HR,2019-03-15,7.0
11,12,Alex,27.0,Female,70000.0,Sales,2018-05-10,8.0
12,13,Chris O'Neil,45.0,Male,120000.0,Marketing,2016-07-22,10.0
13,14,Bob Lee,150.0,Male,70000.0,IT,2017-11-20,15.0
14,15,Alice Wong,32.0,Female,70000.0,Finance,2020-01-01,8.0
15,16,John Doe,28.0,Male,50000.0,Sales,2018-05-10,8.0
16,17,Jane Smith,32.0,Female,60000.0,HR,2019-03-15,7.0
17,18,Bob Lee,150.0,Male,70000.0,IT,2017-11-20,15.0
18,19,Alice Wong,32.0,Female,70000.0,Finance,2020-01-01,8.0
19,20,John Doe,28.0,Male,50000.0,Sales,2018-05-10,8.0

In [6]:
# saving the intermediate dataset
df.to_csv('Stage1.csv', index = False)