In [9]:
import pandas as pd

In [10]:
file_path = 'raw_dataset.csv'

df = pd.read_csv(file_path)
df

,ID,Name,Age,Gender,Salary,Department,Joining_Date,Performance_Score,Remarks
0,1,Alice,40.0,NaN,50000.0,HR,2019-07-01,NaN,NaN
1,2,David,20.0,Male,40000.0,Finance,NaN,4.0,Needs Improvement
2,3,Eva,NaN,NaN,30000.0,NaN,2020-01-15,1.0,Good
3,4,Alice,40.0,Male,NaN,Marketing,2022-11-11,5.0,Good
4,5,Charlie,35.0,F,NaN,finance,2022-11-11,2.0,Needs Improvement
...,...,...,...,...,...,...,...,...,...
205,199,Bob,NaN,Female,30000.0,finance,NaN,1.0,Good
206,96,NaN,35.0,F,30000.0,HR,2019-07-01,100.0,Good
207,5,Charlie,35.0,F,NaN,finance,2022-11-11,2.0,Needs Improvement
208,30,Eva,45.0,Male,NaN,Marketing,2022-11-11,NaN,Average
209,169,Alice,35.0,Unknown,80000.0,it,2022-11-11,3.0,Average

In [26]:
# standardize the data
df['Gender'] = df['Gender'].str.strip().str.capitalize().replace({'Male' : 'M', 'Female': 'F'})

df['Name'] = df['Name'].str.strip().str.capitalize()

df['Department'] = df['Department'].str.strip().str.capitalize().replace({
    'It' : 'IT',
    'Hr' : 'HR'
})

In [15]:
# handling missing values
thres = len(df) * 0.5

df = df.dropna(thresh = thres, axis = 1)

for col in df.columns:
    if df[col].dtype in ['float64', 'int64']:
        df[col].fillna(df[col].median())
    else:
        df[col].fillna(df[col].mode()[0])

In [16]:
# convert the date and time column to datetime format
df['Joining_Date'] = pd.to_datetime(df['Joining_Date'])
df['Joining_Date'] = df['Joining_Date'].fillna(df['Joining_Date'].mode()[0])

In [20]:
# Ensuring correct data types
df['Age'] = df['Age'].astype(float)
df['Salary'] = df['Salary'].astype(float)
df['Performance_Score'] = df['Performance_Score'].astype(float)

In [29]:
# removing outliers
def remove_outliers(df, col):
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    return df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]

df = (
    df
    .pipe(remove_outliers, 'Age')
    .pipe(remove_outliers, 'Salary')
    .pipe(remove_outliers, 'Performance_Score')
)

df = df.drop_duplicates()

cleaned_path = 'cleaned_dataset.csv'

df.to_csv(cleaned_path, index = False)
df

,ID,Name,Age,Gender,Salary,Department,Joining_Date,Performance_Score,Remarks
1,2,David,20.0,M,40000.0,Finance,2022-11-11,4.0,Needs Improvement
5,6,Eva,35.0,M,60000.0,HR,2021-03-20,1.0,Excellent
6,7,Eva,35.0,NaN,80000.0,IT,2019-07-01,2.0,Excellent
9,10,Charlie,40.0,M,60000.0,HR,2020-01-15,3.0,Good
10,11,Alice,40.0,NaN,50000.0,HR,2021-03-20,5.0,Needs Improvement
...,...,...,...,...,...,...,...,...,...
192,193,Alice,40.0,F,70000.0,Marketing,2021-03-20,5.0,Excellent
193,194,Charlie,25.0,F,40000.0,HR,2022-11-11,1.0,Good
195,196,NaN,40.0,NaN,60000.0,HR,2022-11-11,1.0,Good
197,198,Bob,50.0,NaN,80000.0,Marketing,2022-11-11,1.0,Good
199,200,Eva,20.0,F,80000.0,IT,2019-07-01,4.0,NaN